"""Tests for the analysis layer: cell_metrics, motion, exporters.

Uses both the bundled synthetic sample (regenerated by test_io's fixture) and
small deterministic arrays where the expected answer is known exactly.
"""
import os
import sys

import numpy as np
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
SAMPLE = os.path.join(ROOT, "sample_data", "Pos_demo")

from maskviewer.analysis import (cell_metrics, motion, exporters, state,   # noqa: E402
                                 edge_dynamics)


def _disk(h, w, cy, cx, r):
    yy, xx = np.ogrid[:h, :w]
    return ((yy - cy) ** 2 + (xx - cx) ** 2) <= r * r


# ----------------------------------------------------------- motion (exact)
def test_straight_track_is_maximally_persistent():
    cen = np.column_stack([np.arange(10.0), np.zeros(10)])     # due-east, steady
    d = motion.displacement_metrics(cen, dt_min=2.0)
    assert d["straightness"] == pytest.approx(1.0)
    assert d["net_disp"] == pytest.approx(9.0)
    assert d["mean_speed"] == pytest.approx(0.5)               # 1 px / 2 min
    assert motion.persistence(cen) == pytest.approx(1.0)


def test_straightness_and_persistence_capture_different_things():
    # Out-and-back: net displacement is 0 (straightness 0), but locally the
    # path is mostly straight, so lag-1 direction autocorrelation stays high
    # (steps east,east,west,west → cos = +1,-1,+1 → mean +1/3). This is exactly
    # the speed/shape distinction that keeps the two metrics separate.
    cen = np.array([[0, 0], [1, 0], [2, 0], [1, 0], [0, 0]], float)
    d = motion.displacement_metrics(cen)
    assert d["net_disp"] == pytest.approx(0.0)
    assert d["straightness"] == pytest.approx(0.0)
    assert motion.persistence(cen) == pytest.approx(1.0 / 3.0)


def test_msd_increases_with_lag():
    cen = np.column_stack([np.arange(8.0), np.zeros(8)])
    tau, vals = motion.msd(cen, dt_min=1.0)
    assert tau[0] == 1.0
    assert np.all(np.diff(vals) > 0)


def test_gaps_are_tolerated():
    cen = np.array([[0, 0], [np.nan, np.nan], [2, 0], [3, 0]], float)
    assert motion.displacement_metrics(cen)["n_steps"] == 2


# ------------------------------------------------------- cell_metrics shape
def test_regionprops_on_known_square():
    lab = np.zeros((20, 20), int)
    lab[5:15, 5:15] = 7                       # 10x10 square, id 7
    props = cell_metrics.regionprops_frame(lab, um_per_px=0.5, with_solidity=True)
    assert set(props) == {7}
    r = props[7]
    assert r["area_px"] == 100
    assert r["area_um2"] == pytest.approx(25.0)
    assert r["centroid_x"] == pytest.approx(9.5)
    assert r["eccentricity"] < 0.2            # a square is nearly round
    assert 0.9 <= r["solidity"] <= 1.0


def test_elongated_region_is_eccentric():
    lab = np.zeros((20, 40), int)
    lab[9:11, 2:38] = 1                        # long thin bar
    r = cell_metrics.regionprops_frame(lab)[1]
    assert r["eccentricity"] > 0.95
    assert r["aspect_ratio"] > 5


# --------------------------------------------------------------- exporters
def test_exporters_against_sample():
    from maskviewer.io import load_masks, load_recording
    m = load_masks(os.path.join(SAMPLE, "pipeline_results", "masks.npz"))
    rec = load_recording(os.path.join(SAMPLE, "Pos_demo.ome.tif"))
    n_cells = len(m.cell_ids())

    pc = exporters.per_cell_table(m.labels, rec.um_per_px, rec.time_interval_min)
    assert len(pc) == n_cells
    for col in ("cell_id", "frames_tracked", "mean_area_um2", "straightness",
                "persistence_dir_autocorr", "net_disp_um"):
        assert col in pc.columns

    pf = exporters.per_frame_table(m.labels, rec.um_per_px, rec.time_interval_min)
    assert (pf["area_px"] > 0).all()
    cells_per_frame = sum(int((np.unique(m.labels[t]) > 0).sum())
                          for t in range(m.n_frames))
    assert len(pf) == cells_per_frame                  # one row per cell × frame

    tr = exporters.track_table(m.labels, rec.um_per_px)
    assert len(tr) == cells_per_frame                  # tracks: same present count


def test_export_all_writes_files(tmp_path):
    from maskviewer.io import load_masks
    m = load_masks(os.path.join(SAMPLE, "pipeline_results", "masks.npz"))
    paths = exporters.export_all(m.labels, 0.6523, 10.0, str(tmp_path), "demo_")
    assert set(paths) == {"per_frame", "per_cell", "tracks"}
    for p in paths.values():
        assert os.path.getsize(p) > 0


def test_msd_diffusion_fit_ballistic():
    cen = np.column_stack([np.arange(12.0), np.zeros(12)])     # constant velocity
    tau, vals = motion.msd(cen, dt_min=1.0)
    fit = motion.fit_msd(tau, vals)
    assert fit["alpha"] == pytest.approx(2.0, abs=0.05)        # directed → α≈2
    assert fit["r2"] > 0.99


def test_turning_angles_straight_is_zero():
    cen = np.column_stack([np.arange(6.0), np.zeros(6)])
    assert np.allclose(motion.turning_angles(cen), 0.0)


# --------------------------------------------------------------- state
def test_state_rule():
    # small + round → rounded; big → spread; small + elongated → spread
    assert state.classify_state(500, area_um2=300, eccentricity=0.5) == "rounded"
    assert state.classify_state(5000, area_um2=2000, eccentricity=0.5) == "spread"
    assert state.classify_state(500, area_um2=300, eccentricity=0.95) == "spread"
    assert state.classify_state(500, area_um2=300, eccentricity=0.5, edge=True) == "edge"
    assert state.classify_state(50, area_um2=20, eccentricity=0.5) == "unknown"


def test_regionprops_has_state_and_edge():
    lab = np.zeros((40, 40), int)
    lab[15:25, 15:25] = 1                       # interior 10x10 → not edge
    lab[0:5, 0:5] = 2                           # touches corner → edge
    props = cell_metrics.regionprops_frame(lab, um_per_px=0.65)
    assert props[1]["edge"] is False
    assert props[2]["edge"] is True
    assert props[1]["state"] in state.STATES


# --------------------------------------------------------- edge dynamics
def test_growing_disk_is_protrusion():
    labels = np.zeros((4, 60, 60), int)
    for t, r in enumerate((8, 10, 12, 14)):
        labels[t][_disk(60, 60, 30, 30, r)] = 1
    fr, vel = edge_dynamics.edge_velocity_kymograph(labels, 1, um_per_px=1.0,
                                                    dt_min=1.0, smooth=False)
    assert vel.shape == (3, edge_dynamics.N_SECTORS)
    s = edge_dynamics.edge_summary(vel)
    assert s["net_velocity"] > 0                # expanding boundary
    assert s["protrusion_fraction"] > 0.8
    rfr, rmat = edge_dynamics.radius_kymograph(labels, 1, um_per_px=1.0)
    assert rmat.shape == (4, edge_dynamics.N_SECTORS)
    assert np.nanmedian(rmat[-1]) > np.nanmedian(rmat[0])     # radius grew


def test_cell_frame_table_series():
    from maskviewer.io import load_masks, load_recording
    m = load_masks(os.path.join(SAMPLE, "pipeline_results", "masks.npz"))
    rec = load_recording(os.path.join(SAMPLE, "Pos_demo.ome.tif"))
    cid = int(m.cell_ids()[0])
    cf = cell_metrics.cell_frame_table(m.labels, cid, rec.um_per_px,
                                       rec.time_interval_min, recording=rec)
    for key in ("area", "eccentricity", "state_code", "speed", "turning_angle"):
        assert key in cf["series"]
    assert any(k.startswith("intensity_") for k in cf["series"])
    assert cf["centroid_um"].shape == (m.n_frames, 2)


def test_frame_nn():
    from maskviewer.analysis import neighbors
    nn, cnt = neighbors.frame_nn([0.0, 0.0], [0.0, 10.0], scale=2.0, radius=50.0)
    assert nn[0] == pytest.approx(20.0)            # 10 px × 2 µm/px
    assert list(cnt) == [1, 1]
    nn1, cnt1 = neighbors.frame_nn([0.0], [0.0])    # a lone cell
    assert np.isnan(nn1[0]) and cnt1[0] == 0


def test_disk_circularity_near_one():
    lab = np.zeros((60, 60), int)
    lab[_disk(60, 60, 30, 30, 18)] = 1
    r = cell_metrics.regionprops_frame(lab, with_perimeter=True)[1]
    assert "perimeter_px" in r
    assert 0.85 <= r["circularity"] <= 1.05         # a disk is ~maximally round


def test_available_metrics_and_gating():
    from maskviewer.io import load_masks, load_recording
    m = load_masks(os.path.join(SAMPLE, "pipeline_results", "masks.npz"))
    rec = load_recording(os.path.join(SAMPLE, "Pos_demo.ome.tif"))
    avail = cell_metrics.available_frame_metrics(rec.channel_names)
    for k in ("circularity", "perimeter", "iou_prev", "area_change", "nn_dist",
              "n_neighbors", "solidity", "state_code"):
        assert k in avail
    assert any(k.startswith("membrane_contrast_") for k in avail)
    cid = int(m.cell_ids()[0])
    nh = cell_metrics.centroid_history(m.labels)
    sub = cell_metrics.cell_frame_table(
        m.labels, cid, rec.um_per_px, rec.time_interval_min, recording=rec,
        metrics={"circularity", "nn_dist"}, neighbor_history=nh)
    assert set(sub["series"]) == {"circularity", "nn_dist"}   # only requested


def test_shape_modes_cluster():
    from maskviewer.analysis import shape_modes
    T, H, W = 4, 90, 90
    labels = np.zeros((T, H, W), int)
    for t in range(T):
        labels[t][_disk(H, W, 22, 22, 12)] = 1          # round
        labels[t][_disk(H, W, 22, 60, 12)] = 2          # round
        labels[t][16:28, 45:82] = 3                      # elongated bar
        labels[t][45:82, 16:28] = 4                      # elongated bar
        labels[t][_disk(H, W, 65, 65, 11)] = 5           # round
    model = shape_modes.fit_shape_modes(labels, n_modes=2)
    assert model is not None and model["n_modes"] == 2
    assert 0.0 <= model["entropy"] <= 1.0                # 2 modes → ≤1 bit
    fr, md = shape_modes.cell_mode_series(model, 3)
    assert fr.size == T
    x, y = shape_modes.mode_contour(model["mode_signatures"][0])
    assert x.size == shape_modes.N_POINTS + 1
    # round vs elongated land in different modes
    assert model["by_cell_frame"][(1, 0)] != model["by_cell_frame"][(3, 0)]


def test_convexity_disk_vs_ruffled():
    disk_lab = np.zeros((60, 60), int)
    disk_lab[_disk(60, 60, 30, 30, 18)] = 1
    d = cell_metrics.regionprops_frame(disk_lab, with_perimeter=True)[1]
    assert d["convexity"] > 0.9                          # smooth disk
    cross = np.zeros((60, 60), int)
    cross[26:34, 8:52] = 1
    cross[8:52, 26:34] = 1                                # concave plus shape
    c = cell_metrics.regionprops_frame(cross, with_perimeter=True)[1]
    assert c["convexity"] < d["convexity"]


def test_membrane_metrics():
    from maskviewer.analysis import membrane
    img = np.zeros((40, 40))
    img[15:25, 15:25] = 100.0
    mask = img > 0
    assert membrane.boundary_confidence(mask, img) > 0   # edge has a gradient
    assert membrane.intensity_contrast(mask, img) > 0


def test_fit_furth_runs():
    cen = np.column_stack([np.arange(15.0), np.zeros(15)])
    tau, v = motion.msd(cen, dt_min=1.0)
    fu = motion.fit_furth(tau, v)
    assert np.isfinite(fu["D"]) and np.isfinite(fu["persistence_time"])


def test_per_cell_quality_columns():
    from maskviewer.io import load_masks, load_recording
    m = load_masks(os.path.join(SAMPLE, "pipeline_results", "masks.npz"))
    rec = load_recording(os.path.join(SAMPLE, "Pos_demo.ome.tif"))
    pc = exporters.per_cell_table(m.labels, rec.um_per_px, rec.time_interval_min)
    for c in ("track_quality", "frac_isolated", "area_cv", "persistence_time_min",
              "furth_D_um2_per_min"):
        assert c in pc.columns
    tq = pc["track_quality"].to_numpy(float)
    assert ((tq >= 0) & (tq <= 1)).all()


def test_population_table_and_flower():
    from maskviewer.io import load_masks, load_recording
    from maskviewer.analysis import population
    m = load_masks(os.path.join(SAMPLE, "pipeline_results", "masks.npz"))
    rec = load_recording(os.path.join(SAMPLE, "Pos_demo.ome.tif"))
    df = population.population_table(m.labels, rec.um_per_px, rec.time_interval_min)
    for col in ("cell_id", "frame", "speed", "circularity", "nn_dist_um"):
        assert col in df.columns
    assert "speed" in population.metric_columns(df)
    fl = population.flower_tracks(m.labels, rec.um_per_px)
    assert set(fl) == {int(c) for c in m.cell_ids()}
    for rel in fl.values():                              # each track starts at 0
        assert abs(rel[0, 0]) < 1e-9 and abs(rel[0, 1]) < 1e-9


def test_compare_build_aggregate():
    import types
    from maskviewer.analysis import compare

    def stack(cells):
        T, H, W = 6, 80, 80
        lab = np.zeros((T, H, W), int)
        for cid, (cy, cx) in enumerate(cells, 1):
            for t in range(T):
                lab[t][_disk(H, W, cy, cx + t, 9)] = cid
        return lab

    class FE:
        def __init__(self, label, cond, lab):
            self.label, self.condition, self._l = label, cond, lab

        def load_masks(self):
            return types.SimpleNamespace(labels=self._l)

        def load_recording(self):
            return types.SimpleNamespace(um_per_px=0.65, time_interval_min=10.0)

    entries = [FE("A1", "WT", stack([(20, 15), (50, 15)])),
               FE("B1", "KO", stack([(20, 15), (50, 15), (35, 40)]))]
    prog = []
    pc = compare.build_comparison(entries, progress_cb=lambda i, n: prog.append(i) or True)
    assert set(pc["recording"]) == {"A1", "B1"}
    assert set(pc["condition"]) == {"WT", "KO"}
    per_rec = compare.aggregate(pc)
    assert len(per_rec) == 2 and "n_cells" in per_rec.columns
    assert "mean_area_um2" in compare.metric_columns(pc)
    assert set(compare.by_condition(per_rec, "mean_area_um2")) == {"WT", "KO"}
    assert prog and compare.order_conditions(["KO", "WT"]) == ["WT", "KO"]


def test_cell_series_and_history():
    from maskviewer.io import load_masks
    m = load_masks(os.path.join(SAMPLE, "pipeline_results", "masks.npz"))
    cid = int(m.cell_ids()[0])
    s = cell_metrics.cell_series(m.labels, cid, um_per_px=0.6523, dt_min=10.0)
    assert s["frame"].size > 0
    assert np.all(s["area"] > 0)
    hist = cell_metrics.centroid_history(m.labels)
    assert set(hist) == {int(c) for c in m.cell_ids()}
    assert hist[cid].shape == (m.n_frames, 2)
